version: "2"
services:
  node-redis-api:
    image: node:16 # You can change this to any specific Node.js version
    container_name: node-redis-api
    command: yarn test
    environment:
      NODE_ENV: production
    volumes:
      - ./:/usr/data
    working_dir: /usr/data
    depends_on:
      - redis
    networks:
      - mynetwork
    ports:
      - "3000:3000"

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
